// export const subSections = {
//   "Cuisine-Types": {
//     Italian: ["Pasta", "Pizza", "Lasagna", "Risotto", "Bruschetta"],
//     Mexican: ["Tacos", "Burritos", "Enchiladas", "Guacamole", "Salsa"],
//     Asian: ["Sushi", "Dim-Sum", "Thai-Curry", "Ramen", "Spring-Rolls"],
//     Mediterranean: ["Hummus", "Falafel", "Shakshuka", "Gyro", "Tabbouleh"],
//     American: [
//       "Burgers",
//       "Barbecue",
//       "Mac-and-Cheese",
//       "Fried-Chicken",
//       "Apple-Pie",
//     ],
//   },
//   "Meal-Types": {
//     Breakfast: [
//       "Pancakes",
//       "Smoothies",
//       "Eggs-Benedict",
//       "Avocado-Toast",
//       "Overnight-Oats",
//     ],
//     Lunch: ["Salads", "Sandwiches", "Soups", "Wraps", "Quiches"],
//     Dinner: [
//       "Roasted-Chicken",
//       "Stir-Fry",
//       "Steak",
//       "Casseroles",
//       "Pasta-Dishes",
//     ],
//     Snacks: [
//       "Chips-and-Dip",
//       "Fruit-Smoothies",
//       "Energy-Balls",
//       "Nuts-and-Seeds",
//       "Cheese-Platter",
//     ],
//     Desserts: ["Brownies", "Cheesecake", "Cookies", "Ice-Cream", "Fruit-Tarts"],
//   },
//   "Dietary-Preferences": {
//     Vegetarian: [
//       "Vegetable-Stir-Fry",
//       "Lentil-Soup",
//       "Stuffed-Peppers",
//       "Chickpea-Curry",
//     ],
//     Vegan: ["Tofu-Scramble", "Vegan-Burger", "Vegan-Soups", "Fruit-Smoothies"],
//     "Gluten-Free": [
//       "Quinoa-Salad",
//       "Gluten-Free-Pasta",
//       "Rice-Bowls",
//       "Polenta-Cakes",
//     ],
//     Keto: [
//       "Zucchini-Noodles",
//       "Avocado-Salads",
//       "Keto-Soups",
//       "Cheese-Crackers",
//     ],
//     Paleo: [
//       "Grilled-Meats",
//       "Roasted-Vegetables",
//       "Egg-and-Bacon-Muffins",
//       "Fruit-Bowls",
//     ],
//   },
//   "Cooking-Techniques": {
//     Baking: ["Cakes", "Bread", "Pastries", "Cookies", "Muffins"],
//     Grilling: ["Steaks", "Vegetables", "Chicken-Wings", "Fish-Fillets"],
//     Roasting: ["Vegetables", "Meats", "Nuts", "Potatoes"],
//     Sautéing: ["Stir-Fries", "Sautéed-Vegetables", "Egg-Dishes", "Seafood"],
//     Boiling: ["Pasta", "Rice", "Soups", "Eggs", "Potatoes"],
//   },
//   Ingredients: {
//     Fruits: [
//       "Apples",
//       "Bananas",
//       "Berries",
//       "Citrus-Fruits",
//       "Tropical-Fruits",
//     ],
//     Vegetables: [
//       "Leafy-Greens",
//       "Root-Vegetables",
//       "Cruciferous-Vegetables",
//       "Squash",
//     ],
//     Proteins: ["Chicken", "Beef", "Tofu", "Legumes", "Seafood"],
//     Grains: ["Rice", "Quinoa", "Oats", "Wheat", "Barley"],
//     "Spices-and-Herbs": ["Basil", "Cilantro", "Cumin", "Paprika", "Rosemary"],
//   },
//   Drinks: {
//     "Non-Alcoholic": [
//       "Smoothies",
//       "Juices",
//       "Mocktails",
//       "Iced-Tea",
//       "Lemonade",
//     ],
//     Cocktails: ["Margarita", "Mojito", "Martini", "Old-Fashioned", "Negroni"],
//     Wine: [
//       "Red-Wine",
//       "White-Wine",
//       "Rosé",
//       "Sparkling-Wine",
//       "Fortified-Wine",
//     ],
//     Beer: ["Lager", "Ale", "Stout", "IPA", "Wheat-Beer"],
//     "Coffee-and-Tea": [
//       "Espresso",
//       "Latte",
//       "Green-Tea",
//       "Black-Tea",
//       "Herbal-Tea",
//     ],
//   },
//   "Special-Occasions": {
//     Holidays: [
//       "Christmas-Dinner",
//       "Thanksgiving-Feast",
//       "Easter-Brunch",
//       "Halloween-Treats",
//     ],
//     Parties: [
//       "Finger-Foods",
//       "Buffet-Options",
//       "Themed-Cocktails",
//       "Appetizers",
//     ],
//     Weekends: [
//       "Brunch-Recipes",
//       "Barbecue-Ideas",
//       "Comfort-Food",
//       "Family-Dinners",
//     ],
//     "Healthy-Eating": [
//       "Low-Calorie-Recipes",
//       "Whole-Foods",
//       "Superfoods",
//       "Nutritious-Snacks",
//     ],
//     Festivals: [
//       "Carnival-Food",
//       "Street-Food",
//       "Seasonal-Recipes",
//       "Local-Specialties",
//     ],
//   },
//   "Recipe-Formats": {
//     "Quick-Meals": [
//       "30-Minute-Dinners",
//       "One-Pot-Recipes",
//       "Sheet-Pan-Meals",
//       "Quick-Soups",
//     ],
//     "Slow-Cooker": ["Stews", "Chili", "Pulled-Pork", "Slow-Cooked-Chicken"],
//     "Instant-Pot": ["Rice-Dishes", "Soups", "Stews", "Pressure-Cooked-Meats"],
//     "Batch-Cooking": [
//       "Freezer-Meals",
//       "Meal-Prepping",
//       "Large-Batch-Soups",
//       "Make-Ahead-Salads",
//     ],
//     "No-Cook": ["Salads", "Wraps", "Smoothies", "Cold-Soups"],
//   },
//   "Cooking-Tips": {
//     "Meal-Prepping": [
//       "Batch-Cooking",
//       "Portion-Control",
//       "Storage-Tips",
//       "Recipe-Planning",
//     ],
//     "Flavor-Enhancement": [
//       "Seasoning-Tips",
//       "Sauce-Recipes",
//       "Herb-Usage",
//       "Cooking-Times",
//     ],
//     "Kitchen-Skills": [
//       "Knife-Techniques",
//       "Ingredient-Substitutions",
//       "Cooking-Times",
//       "Presentation-Tips",
//     ],
//     "Health-Tips": [
//       "Reducing-Sodium",
//       "Healthy-Fats",
//       "Balancing-Nutrients",
//       "Low-Sugar-Options",
//     ],
//     "Sustainable-Cooking": [
//       "Local-Ingredients",
//       "Reducing-Waste",
//       "Eco-Friendly-Packaging",
//       "Seasonal-Cooking",
//     ],
//   },
//   "Food-Culture": {
//     "Food-History": [
//       "Ancient-Recipes",
//       "Culinary-Traditions",
//       "Food-Origin-Stories",
//     ],
//     "Culinary-Regions": [
//       "Regional-Specialties",
//       "Food-Festivals",
//       "Culinary-Tours",
//     ],
//     "Food-Photography": [
//       "Plating-Techniques",
//       "Lighting-Tips",
//       "Editing-Photos",
//       "Food-Styling",
//     ],
//     "Culinary-Techniques": ["Fermentation", "Pickling", "Smoking", "Sous-Vide"],
//     "Food-Pairings": [
//       "Wine-Pairings",
//       "Cheese-Pairings",
//       "Spice-Pairings",
//       "Seasonal-Pairings",
//     ],
//   },
// };

// export const subSections = {
//   "Cuisine-Types": {
//     Italian: ["Pasta", "Pizza", "Lasagna", "Risotto", "Bruschetta"],
//     Mexican: ["Tacos", "Burritos", "Enchiladas", "Guacamole", "Salsa"],
//     Asian: ["Sushi", "Dim-Sum", "Thai-Curry", "Ramen", "Spring-Rolls"],
//     Mediterranean: ["Hummus", "Falafel", "Shakshuka", "Gyro", "Tabbouleh"],
//     American: [
//       "Burgers",
//       "Barbecue",
//       "Mac-and-Cheese",
//       "Fried-Chicken",
//       "Apple-Pie",
//     ],
//     Indian: ["Butter-Chicken", "Biryani", "Samosas", "Paneer-Tikka", "Dal"],
//     French: [
//       "Croissants",
//       "Quiche",
//       "Ratatouille",
//       "Coq-au-Vin",
//       "Crème-Brûlée",
//     ],
//   },
//   "Meal-Types": {
//     Breakfast: [
//       "Pancakes",
//       "Smoothies",
//       "Eggs-Benedict",
//       "Avocado-Toast",
//       "Overnight-Oats",
//     ],
//     Lunch: ["Salads", "Sandwiches", "Soups", "Wraps", "Quiches"],
//     Dinner: [
//       "Roasted-Chicken",
//       "Stir-Fry",
//       "Steak",
//       "Casseroles",
//       "Pasta-Dishes",
//     ],
//     Snacks: [
//       "Chips-and-Dip",
//       "Fruit-Smoothies",
//       "Energy-Balls",
//       "Nuts-and-Seeds",
//       "Cheese-Platter",
//     ],
//     Desserts: ["Brownies", "Cheesecake", "Cookies", "Ice-Cream", "Fruit-Tarts"],
//   },
//   "Dietary-Preferences": {
//     Vegetarian: [
//       "Vegetable-Stir-Fry",
//       "Lentil-Soup",
//       "Stuffed-Peppers",
//       "Chickpea-Curry",
//     ],
//     Vegan: ["Tofu-Scramble", "Vegan-Burger", "Vegan-Soups", "Fruit-Smoothies"],
//     "Gluten-Free": [
//       "Quinoa-Salad",
//       "Gluten-Free-Pasta",
//       "Rice-Bowls",
//       "Polenta-Cakes",
//     ],
//     Keto: [
//       "Zucchini-Noodles",
//       "Avocado-Salads",
//       "Keto-Soups",
//       "Cheese-Crackers",
//     ],
//     Paleo: [
//       "Grilled-Meats",
//       "Roasted-Vegetables",
//       "Egg-and-Bacon-Muffins",
//       "Fruit-Bowls",
//     ],
//     "Low-Carb": [
//       "Cauliflower-Rice",
//       "Zucchini-Lasagna",
//       "Lettuce-Wraps",
//       "Protein-Bowls",
//     ],
//   },
//   "Cooking-Techniques": {
//     Baking: ["Cakes", "Bread", "Pastries", "Cookies", "Muffins"],
//     Grilling: ["Steaks", "Vegetables", "Chicken-Wings", "Fish-Fillets"],
//     Roasting: ["Vegetables", "Meats", "Nuts", "Potatoes"],
//     Sautéing: ["Stir-Fries", "Sautéed-Vegetables", "Egg-Dishes", "Seafood"],
//     Boiling: ["Pasta", "Rice", "Soups", "Eggs", "Potatoes"],
//     Steaming: ["Dumplings", "Fish", "Vegetables", "Rice"],
//     Frying: ["Fried-Chicken", "Tempura", "Falafel", "Donuts"],
//   },
//   "Recipe-Formats": {
//     "Quick-Meals": [
//       "30-Minute-Dinners",
//       "One-Pot-Recipes",
//       "Sheet-Pan-Meals",
//       "Quick-Soups",
//     ],
//     "Slow-Cooker": ["Stews", "Chili", "Pulled-Pork", "Slow-Cooked-Chicken"],
//     "Instant-Pot": ["Rice-Dishes", "Soups", "Stews", "Pressure-Cooked-Meats"],
//     "Batch-Cooking": [
//       "Freezer-Meals",
//       "Meal-Prepping",
//       "Large-Batch-Soups",
//       "Make-Ahead-Salads",
//     ],
//     "No-Cook": ["Salads", "Wraps", "Smoothies", "Cold-Soups"],
//     "One-Bowl-Meals": [
//       "Buddha-Bowls",
//       "Poke-Bowls",
//       "Grain-Bowls",
//       "Oatmeal-Bowls",
//     ],
//   },
//   "Modern-Trends": {
//     "Plant-Based": [
//       "Vegan-Cheese",
//       "Jackfruit-Tacos",
//       "Cauliflower-Steak",
//       "Plant-Based-Meatballs",
//     ],
//     "Fusion-Cuisine": [
//       "Sushi-Burritos",
//       "Kimchi-Tacos",
//       "Ramen-Burgers",
//       "Curry-Pizza",
//     ],
//     "Healthy-Swaps": [
//       "Zoodles-instead-of-Pasta",
//       "Cauliflower-Rice",
//       "Avocado-Chocolate-Mousse",
//       "Chia-Pudding",
//     ],
//     "Fermented-Foods": ["Kombucha", "Kimchi", "Sauerkraut", "Sourdough-Bread"],
//   },
//   "Seasonal-Recipes": {
//     Spring: ["Asparagus-Risotto", "Strawberry-Salad", "Lemon-Desserts"],
//     Summer: ["Grilled-Corn", "Watermelon-Salad", "Berry-Smoothies"],
//     Fall: ["Pumpkin-Soup", "Apple-Crisp", "Butternut-Squash-Pasta"],
//     Winter: ["Hot-Chocolate", "Hearty-Stews", "Gingerbread-Cookies"],
//   },
// };

export const subSections = {
  "Cuisine-Types": {
    Italian: ["Pasta", "Pizza", "Lasagna", "Risotto", "Bruschetta"],
    Mexican: ["Tacos", "Burritos", "Enchiladas", "Guacamole", "Salsa"],
    Asian: ["Sushi", "Dim-Sum", "Thai-Curry", "Ramen", "Spring-Rolls"],
    Mediterranean: ["Hummus", "Falafel", "Shakshuka", "Gyro", "Tabbouleh"],
    American: [
      "Burgers",
      "Barbecue",
      "Mac-and-Cheese",
      "Fried-Chicken",
      "Apple-Pie",
    ],
    Indian: ["Butter-Chicken", "Biryani", "Samosas", "Paneer-Tikka", "Dal"],
    French: [
      "Croissants",
      "Quiche",
      "Ratatouille",
      "Coq-au-Vin",
      "Crème-Brûlée",
    ],
    Japanese: ["Sashimi", "Tempura", "Udon", "Miso-Soup", "Takoyaki"],
    Greek: ["Moussaka", "Souvlaki", "Spanakopita", "Tzatziki", "Baklava"],
    Spanish: ["Paella", "Tapas", "Gazpacho", "Churros", "Tortilla-Española"],
  },
  "Meal-Types": {
    Breakfast: [
      "Pancakes",
      "Smoothies",
      "Eggs-Benedict",
      "Avocado-Toast",
      "Overnight-Oats",
    ],
    Lunch: ["Salads", "Sandwiches", "Soups", "Wraps", "Quiches"],
    Dinner: [
      "Roasted-Chicken",
      "Stir-Fry",
      "Steak",
      "Casseroles",
      "Pasta-Dishes",
    ],
    Snacks: [
      "Chips-and-Dip",
      "Fruit-Smoothies",
      "Energy-Balls",
      "Nuts-and-Seeds",
      "Cheese-Platter",
    ],
    Desserts: ["Brownies", "Cheesecake", "Cookies", "Ice-Cream", "Fruit-Tarts"],
    Brunch: [
      "French-Toast",
      "Eggs-Florentine",
      "Mimosas",
      "Bagels",
      "Frittatas",
    ],
  },
  "Dietary-Preferences": {
    Vegetarian: [
      "Vegetable-Stir-Fry",
      "Lentil-Soup",
      "Stuffed-Peppers",
      "Chickpea-Curry",
    ],
    Vegan: ["Tofu-Scramble", "Vegan-Burger", "Vegan-Soups", "Fruit-Smoothies"],
    "Gluten-Free": [
      "Quinoa-Salad",
      "Gluten-Free-Pasta",
      "Rice-Bowls",
      "Polenta-Cakes",
    ],
    Keto: [
      "Zucchini-Noodles",
      "Avocado-Salads",
      "Keto-Soups",
      "Cheese-Crackers",
    ],
    Paleo: [
      "Grilled-Meats",
      "Roasted-Vegetables",
      "Egg-and-Bacon-Muffins",
      "Fruit-Bowls",
    ],
    "Low-Carb": [
      "Cauliflower-Rice",
      "Zucchini-Lasagna",
      "Lettuce-Wraps",
      "Protein-Bowls",
    ],
    "Dairy-Free": [
      "Coconut-Yogurt",
      "Almond-Milk-Smoothies",
      "Cashew-Cheese",
      "Dairy-Free-Ice-Cream",
    ],
  },
  Ingredients: {
    Fruits: [
      "Apples",
      "Bananas",
      "Berries",
      "Citrus-Fruits",
      "Tropical-Fruits",
    ],
    Vegetables: [
      "Leafy-Greens",
      "Root-Vegetables",
      "Cruciferous-Vegetables",
      "Squash",
    ],
    Proteins: ["Chicken", "Beef", "Tofu", "Legumes", "Seafood"],
    Grains: ["Rice", "Quinoa", "Oats", "Wheat", "Barley"],
    "Spices-and-Herbs": ["Basil", "Cilantro", "Cumin", "Paprika", "Rosemary"],
  },
  "Cooking-Techniques": {
    Baking: ["Cakes", "Bread", "Pastries", "Cookies", "Muffins"],
    Grilling: ["Steaks", "Vegetables", "Chicken-Wings", "Fish-Fillets"],
    Roasting: ["Vegetables", "Meats", "Nuts", "Potatoes"],
    Sautéing: ["Stir-Fries", "Sautéed-Vegetables", "Egg-Dishes", "Seafood"],
    Boiling: ["Pasta", "Rice", "Soups", "Eggs", "Potatoes"],
    Steaming: ["Dumplings", "Fish", "Vegetables", "Rice"],
    Frying: ["Fried-Chicken", "Tempura", "Falafel", "Donuts"],
    Smoking: [
      "Smoked-Brisket",
      "Smoked-Salmon",
      "Smoked-Cheese",
      "Smoked-Ribs",
    ],
  },
  "Recipe-Formats": {
    "Quick-Meals": [
      "30-Minute-Dinners",
      "One-Pot-Recipes",
      "Sheet-Pan-Meals",
      "Quick-Soups",
    ],
    "Slow-Cooker": ["Stews", "Chili", "Pulled-Pork", "Slow-Cooked-Chicken"],
    "Instant-Pot": ["Rice-Dishes", "Soups", "Stews", "Pressure-Cooked-Meats"],
    "Batch-Cooking": [
      "Freezer-Meals",
      "Meal-Prepping",
      "Large-Batch-Soups",
      "Make-Ahead-Salads",
    ],
    "No-Cook": ["Salads", "Wraps", "Smoothies", "Cold-Soups"],
    "One-Bowl-Meals": [
      "Buddha-Bowls",
      "Poke-Bowls",
      "Grain-Bowls",
      "Oatmeal-Bowls",
    ],
    "Kid-Friendly": [
      "Mini-Pizzas",
      "Chicken-Nuggets",
      "Mac-and-Cheese",
      "Fruit-Kebabs",
    ],
  },
  "Modern-Trends": {
    "Plant-Based": [
      "Vegan-Cheese",
      "Jackfruit-Tacos",
      "Cauliflower-Steak",
      "Plant-Based-Meatballs",
    ],
    "Fusion-Cuisine": [
      "Sushi-Burritos",
      "Kimchi-Tacos",
      "Ramen-Burgers",
      "Curry-Pizza",
    ],
    "Healthy-Swaps": [
      "Zoodles-instead-of-Pasta",
      "Cauliflower-Rice",
      "Avocado-Chocolate-Mousse",
      "Chia-Pudding",
    ],
    "Fermented-Foods": ["Kombucha", "Kimchi", "Sauerkraut", "Sourdough-Bread"],
    "Zero-Waste-Cooking": [
      "Broth-from-Scraps",
      "Leftover-Frittatas",
      "Vegetable-Peel-Chips",
      "Stale-Bread-Pudding",
    ],
  },
  "Seasonal-Recipes": {
    Spring: ["Asparagus-Risotto", "Strawberry-Salad", "Lemon-Desserts"],
    Summer: ["Grilled-Corn", "Watermelon-Salad", "Berry-Smoothies"],
    Fall: ["Pumpkin-Soup", "Apple-Crisp", "Butternut-Squash-Pasta"],
    Winter: ["Hot-Chocolate", "Hearty-Stews", "Gingerbread-Cookies"],
    Holiday: [
      "Christmas-Ham",
      "Thanksgiving-Turkey",
      "Easter-Lamb",
      "Valentine's-Chocolate-Fondue",
    ],
  },
  "Global-Flavors": {
    "Middle-Eastern": ["Shawarma", "Kebab", "Baklava", "Fattoush"],
    "South-American": ["Empanadas", "Ceviche", "Feijoada", "Arepas"],
    African: ["Jollof-Rice", "Tagine", "Bobotie", "Injera"],
    Caribbean: ["Jerk-Chicken", "Plantains", "Roti", "Callaloo"],
    Nordic: ["Gravlax", "Smørrebrød", "Köttbullar", "Lingonberry-Jam"],
  },
  "Special-Occasions": {
    Birthday: ["Birthday-Cake", "Cupcakes", "Party-Pizza", "Cocktails"],
    Anniversary: ["Champagne", "Lobster-Dinner", "Chocolate-Fondue"],
    Picnic: ["Sandwiches", "Pasta-Salad", "Fruit-Platter", "Lemonade"],
    Potluck: ["Casseroles", "Dips", "Brownies", "Deviled-Eggs"],
    "Game-Day": ["Wings", "Nachos", "Sliders", "Beer-Pretzels"],
  },
};
